# Generated by Django 3.0.6 on 2020-05-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaquita', '0001_initial'),
        ('news', '0005_auto_20200515_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vaquita.CustomImage'),
        ),
    ]
