# Generated by Django 3.0.6 on 2020-05-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200525_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypage',
            name='anonymous',
        ),
    ]
