# Generated by Django 3.0.6 on 2020-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200602_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialnotice',
            name='color',
        ),
        migrations.AddField(
            model_name='specialnotice',
            name='background_color',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialnotice',
            name='hover_color',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialnotice',
            name='link_color',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
