# Generated by Django 3.0.6 on 2020-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200603_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialnotice',
            name='background_color',
            field=models.CharField(max_length=7, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='specialnotice',
            name='hover_color',
            field=models.CharField(max_length=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specialnotice',
            name='link_color',
            field=models.CharField(max_length=7, verbose_name=''),
        ),
    ]
