# Generated by Django 2.2 on 2019-04-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
