# Generated by Django 2.2 on 2019-04-13 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_auto_20190410_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='released',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Release dates in the future will not be visible on the site', null=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('photo', models.ImageField(height_field='height', upload_to='photos', width_field='width')),
                ('caption', models.TextField(default='')),
                ('width', models.IntegerField(blank=True, default=0)),
                ('height', models.IntegerField(blank=True, default=0)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
