# Generated by Django 2.2 on 2019-04-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190414_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
