# Generated by Django 2.2 on 2019-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_pressrelease_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, default=0.0)),
                ('lng', models.FloatField(blank=True, default=0.0)),
                ('site', models.CharField(max_length=255)),
                ('join', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
            ],
        ),
    ]
