# Generated by Django 2.1.7 on 2019-03-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_merge_20190214_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('when', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ActionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Contact')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actions.ActionRole')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('action', 'contact', 'role')},
        ),
    ]
