# Generated by Django 2.2 on 2019-04-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
