# Generated by Django 2.2 on 2019-04-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_merge_20190214_1427'),
        ('actions', '0004_auto_20190405_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('responded', models.DateTimeField(blank=True, null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Contact')),
            ],
        ),
    ]
