# Generated by Django 2.2 on 2019-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_attendee_mutual_committment'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
    ]
