# Generated by Django 2.2 on 2019-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_action_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
