# Generated by Django 2.2 on 2019-04-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_attendee_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='available_roles',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
