# Generated by Django 2.2 on 2019-04-13 13:37

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_action_available_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='available_roles',
            field=models.CharField(blank=True, default='', help_text='List of comma-separated strings', max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown formatted'),
        ),
        migrations.AlterField(
            model_name='action',
            name='public',
            field=models.BooleanField(blank=True, default=True, help_text='Whether this action should be listed publicly'),
        ),
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.SlugField(help_text='Short form of the title, for URLs', unique=True),
        ),
    ]
