# Generated by Django 2.2 on 2019-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190413_0937'),
        ('actions', '0011_auto_20190413_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='photos',
            field=models.ManyToManyField(to='info.Photo'),
        ),
    ]
