# Generated by Django 2.2 on 2019-04-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_auto_20190414_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='show_commitment',
            field=models.BooleanField(blank=True, default=True, help_text='Whether to show the conditional commitment fields'),
        ),
    ]
