# Generated by Django 2.2 on 2019-04-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_action_show_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='notified',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
