# Generated by Django 2.2 on 2019-04-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_attendee_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='mutual_committment',
            new_name='mutual_commitment',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='mutual_commitment',
            field=models.IntegerField(blank=True, db_column='mutual_committment', default=0),
        ),
    ]
