# Generated by Django 2.2 on 2019-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_auto_20190424_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='max_participants',
            field=models.IntegerField(blank=True, default=0, help_text='Maximun number of people allowed to register'),
        ),
    ]
