# Generated by Django 2.2 on 2019-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_action_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='accessibility',
            field=models.TextField(default='', help_text='Indicate what the accessibility accomodations are for this location.'),
        ),
    ]
