# Generated by Django 2.2 on 2019-06-03 15:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('actions', '0018_action_accessibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Attendees will automatically be tagged with these tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
