# Generated by Django 2.2.3 on 2019-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_auto_20190707_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='show_commitment',
            field=models.BooleanField(blank=True, default=False, help_text='Whether to show the conditional commitment fields'),
        ),
    ]
