# Generated by Django 3.0.6 on 2020-05-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaquita', '0001_initial'),
        ('actions', '0021_auto_20190718_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vaquita.CustomImage'),
        ),
    ]
