# Generated by Django 3.0.6 on 2020-05-31 21:02

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0022_action_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, default='', help_text='Markdown formatted'),
        ),
    ]
