# Generated by Django 3.0.13 on 2021-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0024_auto_20211023_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Check this if the event is online (virtual zoom or other video conferencing)'),
        ),
    ]
