# Generated by Django 3.2.8 on 2023-06-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_action_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='send_reminders',
            field=models.BooleanField(blank=True, default=True, help_text='Send reminders for the event to participants', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='virtual',
            field=models.BooleanField(default=False, help_text='Check this if the event is online (virtual zoom or other video conferencing) and enter the url below (including the https part)'),
        ),
    ]
