# Generated by Django 2.2 on 2019-04-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_phone_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('purpose', models.TextField(default='')),
                ('color', models.CharField(blank=True, default='#fff', max_length=50)),
                ('leads', models.ManyToManyField(blank=True, related_name='leads', to='contacts.Contact')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='contacts.Contact')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.Circle')),
            ],
        ),
    ]
