# Generated by Django 2.2 on 2019-05-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20190429_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='email',
            field=models.EmailField(blank=True, help_text='Public email address for this group', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='purpose',
            field=models.TextField(default='', help_text='Describe the mandates for this group'),
        ),
    ]
