# Generated by Django 2.2 on 2019-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20190430_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
