# Generated by Django 2.2 on 2019-05-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_membershiprequest_confirm_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_set', to='contacts.Contact'),
        ),
    ]
