# Generated by Django 2.2 on 2019-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_auto_20190503_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='sensitive_info',
            field=models.TextField(default='', help_text='Information for members only'),
        ),
    ]
