# Generated by Django 2.2 on 2019-05-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_circle_sensitive_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='sensitive_info',
            field=models.TextField(blank=True, default='', help_text='Information for members only'),
        ),
    ]
