# Generated by Django 2.2 on 2019-05-16 20:51

from django.db import migrations


def copy_members(apps, schema_editor):
    Circle = apps.get_model('circles', 'Circle')
    CircleMember = apps.get_model('circles', 'CircleMember')

    for circle in Circle.objects.all():
        for member in circle.members.all():
            CircleMember.objects.create(circle=circle, contact=member, role='member')
        for member in circle.leads.all():
            CircleMember.objects.create(circle=circle, contact=member, role='lead')


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0008_circlemember'),
    ]

    operations = [
        migrations.RunPython(copy_members)
    ]
