# Generated by Django 2.2 on 2019-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0011_circle_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='available_roles',
            field=models.CharField(blank=True, default='int,ext,member', max_length=255),
        ),
    ]
