# Generated by Django 2.2 on 2019-05-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0012_circle_available_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='role_description',
            field=models.TextField(blank=True, default='', help_text='Describe additional roles (markdown format'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='available_roles',
            field=models.CharField(blank=True, default='int,ext,member', help_text='Comma-separated names of roles', max_length=255),
        ),
    ]
