# Generated by Django 2.2 on 2019-06-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0014_circlejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlejob',
            name='filled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circlejob',
            name='filled',
            field=models.ForeignKey(blank=True, help_text='Who will fill this job?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_job_set', to='contacts.Contact'),
        ),
    ]
