# Generated by Django 2.2 on 2019-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0015_auto_20190603_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlejob',
            name='asap',
            field=models.BooleanField(blank=True, default=False, help_text='This job needs to be filled as soon as possible'),
        ),
    ]
