# Generated by Django 2.2 on 2019-06-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0016_circlejob_asap'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlejob',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
