# Generated by Django 2.2.2 on 2019-06-03 20:12

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0017_circlejob_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='purpose',
            field=markdownx.models.MarkdownxField(default='', help_text='Describe the mandates for this group'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='role_description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Describe additional roles (markdown format'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='sensitive_info',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Information for members only'),
        ),
        migrations.AlterField(
            model_name='circlejob',
            name='job',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.CreateModel(
            name='Couch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('availability', markdownx.models.MarkdownxField(default='', help_text='Enter dates/times this room is available')),
                ('info', markdownx.models.MarkdownxField(default='')),
                ('public', models.BooleanField(db_index=True, default=False, help_text='Show publicly')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
    ]
