# Generated by Django 2.2.1 on 2019-06-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0018_auto_20190603_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couch',
            options={'verbose_name_plural': 'couches'},
        ),
    ]
