# Generated by Django 3.0.6 on 2020-05-19 20:28

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contacts', '0005_auto_20191219_0858'),
        ('circles', '0020_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedVolunteerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles_taggedvolunteerrequest_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField(blank=True, default='')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Contact')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='circles.TaggedVolunteerRequest', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='taggedvolunteerrequest',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.VolunteerRequest'),
        ),
    ]
