# Generated by Django 3.0.6 on 2020-05-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0022_auto_20200519_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
