# Generated by Django 3.0.6 on 2020-06-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20191219_0858'),
        ('circles', '0023_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrequest',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('c', 'contacted'), ('r', 'replied'), ('s', 'call scheduled'), ('l', 'called'), ('j', 'joined')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
