# Generated by Django 3.0.6 on 2020-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0024_auto_20200604_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrequest',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
