# Generated by Django 3.0.12 on 2021-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0026_auto_20200604_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('c', 'Contacted'), ('r', 'Replied'), ('s', 'Scheduled'), ('l', 'Called'), ('j', 'Joined')], default='n', max_length=1),
        ),
    ]
