# Generated by Django 3.2.8 on 2023-06-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0027_auto_20210222_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=127)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=127)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
